<table>
<tr style="border:none;">
<td style="border:none;"><a href="https://fra.utn.edu.ar/">
<image src="https://raw.githubusercontent.com/epplugins/UTN/main/assets/img/logoUTN-500.svg"  width="100">
</a></td>
<td style="border:none;">Física 2<br>2024<br>Electromagnetismo<br>Material para trabajo en clase.
</td>
</tr>
</table> 

# Campo Eléctrico

<table>
<tr style="border:none;">
<td style="border:none;"><a href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.es"><image src="https://raw.githubusercontent.com/epplugins/UTN/main/assets/img/by-nc-sa.svg" width="70" /></a></td>
<td style="border:none;">Edgardo Palazzo (epalazzo@fra.utn.edu.ar)
</td>
</tr>
</table>

---

**Tabla de contenidos**<a id='toc0_'></a>    
- 1. [Campo de una carga](#toc1_)    
- 2. [Campo de dos cargas](#toc2_)    
  - 2.1. [El dipolo eléctrico](#toc2_1_)    
  - 2.2. [Dos cargas de diferente valor](#toc2_2_)    
  - 2.3. [Ejercicio](#toc2_3_)    
  - 2.4. [Más de dos cargas](#toc2_4_)    

<!-- vscode-jupyter-toc-config
	numbering=true
	anchor=true
	flat=false
	minLevel=2
	maxLevel=6
	/vscode-jupyter-toc-config -->
<!-- THIS CELL WILL BE REPLACED ON TOC UPDATE. DO NOT WRITE YOUR TEXT IN THIS CELL -->

In [8]:
import matplotlib.pyplot as plt
import numpy as np

## 1. <a id='toc1_'></a>[Campo de una carga](#toc0_)

El campo eléctrico producido por una carga puntual $q_0$ ubicada en la posición $\vec{\text{x}}_0$ puede escribirse como:
$$
\vec{E}(\vec{\text{x}}) = \frac{1}{4\pi\varepsilon_0} \frac{q}{|\vec{\text{r}}|^2} \hat{\text{r}}\, , \tag{1}
$$
donde
  * $|\vec{r}|$ es la distancia entre la posición de la partícula cargada ($\vec{\text{x}}_0$) y la posición donde se quiere obtener el vector de campo eléctrico ($\vec{\text{x}}$)
  * $\hat{\text{r}}$ es el vector unitario en la dirección desde $\vec{\text{x}}_0$ hacia $\vec{\text{x}}$

según se muestra en la siguiente figura.

<div>
       <a href="https://fra.utn.edu.ar/">
       <image src="https://raw.githubusercontent.com/epplugins/UTN/main/electromagnetismo/img/em01_una_carga.svg">
       </a>
</div>

Si el vector unitario se reescribe como $\hat{r} = \vec{\text{r}}/|\vec{\text{r}}|$, la expresión para el campo resulta:
$$
\vec{E}(\vec{\text{x}}) = \frac{1}{4\pi\varepsilon_0} \frac{q}{|\vec{\text{r}}|^3} \vec{\text{r}}\, . \tag{2}
$$

Para escribir un código que calcule el campo eléctrico es conveniente utilizar una expresión con las coordenadas del punto campo y la posición de la carga explícitas. El código que utilizaremos reproduce la siguiente expresión:
$$
\vec{E}(x,y,z) = \frac{1}{4\pi\varepsilon_0} \frac{q}{\left ((x-x_0)^2 + (y-y_0)^2 + (z-z_0)^2 \right )^{3/2}} \left ( (x-x_0)\hat{i} + (y-y_0)\hat{j} + (z-z_0)\hat{k} \right ) . \tag{3}
$$

Definición de una función que calcula las componentes del campo eléctrico en la posición $(x,y,z)$ cuando se tiene una carga de $1~\text{nC}$ en el origen:

In [6]:
def E(x,y,z):
    """Calcula las componentes del campo eléctrico en N/C.
    Ingresar valores de x,y,z en metros y q en coulomb.
    """
    q = 1E-9
    x0 = 0
    y0 = 0
    z0 = 0

    r = ((x - x0)**2 + (y - y0)**2 + (z - z0)**2)**(3/2)
    Ei = 9E9 * q * (x - x0) / r
    Ej = 9E9 * q * (y - y0) / r
    Ek = 9E9 * q * (z - z0) / r
    
    return Ei, Ej, Ek

Si queremos el vector campo eléctrico en alguna posición, simplemente se ingresan los valores de $x,y,z$:

In [4]:
E(1,0,0)

(9.0, 0.0, 0.0)

In [9]:
x = np.arange(4)
y = np.arange(4)
z = np.arange(4)
E(x,y,z)

/tmp/ipykernel_12250/329256007.py:11: RuntimeWarning: invalid value encountered in divide
  Ei = 9E9 * q * (x - x0) / r
/tmp/ipykernel_12250/329256007.py:12: RuntimeWarning: invalid value encountered in divide
  Ej = 9E9 * q * (y - y0) / r
/tmp/ipykernel_12250/329256007.py:13: RuntimeWarning: invalid value encountered in divide
  Ek = 9E9 * q * (z - z0) / r


(array([       nan, 1.73205081, 0.4330127 , 0.19245009]),
 array([       nan, 1.73205081, 0.4330127 , 0.19245009]),
 array([       nan, 1.73205081, 0.4330127 , 0.19245009]))

## 2. <a id='toc2_'></a>[Campo de dos cargas](#toc0_)

### 2.1. <a id='toc2_1_'></a>[El dipolo eléctrico](#toc0_)

In [5]:
# some code

### 2.2. <a id='toc2_2_'></a>[Dos cargas de diferente valor](#toc0_)

In [6]:
# some code

### 2.3. <a id='toc2_3_'></a>[Ejercicio](#toc0_)

In [1]:
# Algo, buscar los valores de E, la posición de la carga, o la fuerza sobre una carga.

# Buscar los ángulos para el vector, en posiciones conocidas, luego en cualquier lugar, luego con alguna condición como que apunte en cierta dirección.

### 2.4. <a id='toc2_4_'></a>[Más de dos cargas](#toc0_)